; This file is for the FamiTone2 library and was generated by FamiStudio

music_data_contra:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; 00 : Song 1

.export music_data_contra
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $30 ; 00 : Duty 0
	.word @env0, @env1, @env1
	.byte $00
	.byte $f0 ; 01 : Duty 3
	.word @env0, @env1, @env1
	.byte $00

@env0:
	.byte $cf,$7f,$00,$00
@env1:
	.byte $c0,$7f,$00,$01

@samples:
	.byte $00+.lobyte(FT_DPCM_PTR),$05,$0f	;0 Sample 1 (Pitch:15)

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
	.byte $82, $1a, $c5, $44, $c5, $40, $c5, $36, $c5, $3a, $f9, $e3
@song0ref16:
	.byte $df, $00, $f9, $f9, $f9, $af
@song0ref22:
	.byte $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9
	.byte $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97
	.byte $ff, $28
	.word @song0ref22
	.byte $ff, $28
	.word @song0ref22
	.byte $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $80, $24, $c5, $4a, $c5, $48, $c5, $40, $c5, $44, $f5, $4e, $a5, $52, $bd
	.byte $ff, $2e
	.word @song0ref16
	.byte $ff, $28
	.word @song0ref22
	.byte $ff, $28
	.word @song0ref22
	.byte $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80, $24, $b5, $00, $8d, $52, $b5, $00, $8d, $4e, $b3, $00, $8f, $48, $b3, $00, $8f, $2c, $f5, $1e, $a5, $2c, $bd
	.byte $ff, $2e
	.word @song0ref16
	.byte $ff, $28
	.word @song0ref22
	.byte $ff, $28
	.word @song0ref22
	.byte $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $80, $58, $5c, $00, $c1, $58, $5c, $00, $c1, $58, $5c, $00, $c1, $58, $5c, $00, $c1, $42, $40, $42, $40, $42, $40, $42
	.byte $40, $83, $4f, $41, $46, $8b, $48, $c3, $44, $8b, $46, $8b, $48, $b5, $46, $8b, $48, $8b, $8d, $46, $99, $48, $8b, $00
	.byte $f9, $f9, $f9, $d7
	.byte $ff, $28
	.word @song0ref22
	.byte $ff, $28
	.word @song0ref22
	.byte $ff, $28
	.word @song0ref22
	.byte $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $02, $00, $f9, $d9, $02, $00, $f9, $c1, $02, $00, $a3, $02, $00, $bb
	.byte $ff, $28
	.word @song0ref22
	.byte $ff, $28
	.word @song0ref22
	.byte $ff, $28
	.word @song0ref22
	.byte $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $fd
	.word @song0ch4loop
