; This file is for the FamiTone2 library and was generated by FamiStudio

music_data_contra:
	.byte 4
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; 00 : Song 1
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256 ; 01 : Song 2
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256 ; 02 : Song 3
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256 ; 03 : Song 4

.export music_data_contra
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $30 ; 00 : Duty 0
	.word @env0, @env1, @env1
	.byte $00
	.byte $70 ; 01 : Duty 1
	.word @env0, @env1, @env1
	.byte $00
	.byte $b0 ; 02 : Duty 2
	.word @env0, @env1, @env1
	.byte $00
	.byte $f0 ; 03 : Duty 3
	.word @env0, @env1, @env1
	.byte $00

@env0:
	.byte $cf,$7f,$00,$00
@env1:
	.byte $c0,$7f,$00,$01

@samples:
	.byte $00+.lobyte(FT_DPCM_PTR),$05,$0f	;0 Sample 1 (Pitch:15)
	.byte $02+.lobyte(FT_DPCM_PTR),$25,$0f	;1 Sample 2 (Pitch:15)

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
	.byte $86, $1a, $c5, $44, $c5, $40, $c5, $36, $c5, $3a, $9d, $f9, $f9, $ab
@song0ref18:
	.byte $00, $9d
@song0ref20:
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb
	.byte $ff, $15
	.word @song0ref20
	.byte $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $80, $24, $c5, $4a, $c5, $48, $c5, $40, $c5, $44, $9d, $d7, $4e, $a5, $52, $f9, $a3
	.byte $ff, $17
	.word @song0ref18
	.byte $ff, $15
	.word @song0ref20
	.byte $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80, $24, $b5, $00, $8d, $52, $b5, $00, $8d, $4e, $b3, $00, $8f, $48, $b3, $00, $8f, $2c, $9d, $d7, $1e, $a5, $2c, $f9
	.byte $a3
	.byte $ff, $17
	.word @song0ref18
	.byte $ff, $15
	.word @song0ref20
	.byte $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $80, $58, $5c, $00, $c1, $58, $5c, $00, $c1, $58, $5c, $00, $c1, $58, $5c, $00, $c1, $42, $40, $42, $40, $42, $40, $42
	.byte $40, $83, $4f, $41, $46, $81, $89, $48, $c3, $44, $8b, $46, $8b, $48, $b5, $46, $8b, $48, $99, $46, $99, $48, $8b, $00
	.byte $c5
	.byte $ff, $15
	.word @song0ref20
	.byte $ff, $15
	.word @song0ref20
	.byte $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $02, $00, $f9, $d9, $02, $00, $e3, $d7, $02, $00, $a3, $02, $00, $f9, $c1
	.byte $ff, $15
	.word @song0ref20
	.byte $ff, $15
	.word @song0ref20
	.byte $fd
	.word @song0ch4loop
@song1ch0:
	.byte $fb, $01
@song1ch0loop:
	.byte $84
@song1ref5:
	.byte $32, $8d, $4a, $8d, $40, $8d, $3a, $8d, $4a, $8b, $40, $8b, $3a, $8f, $00, $8f, $34, $8d, $4c, $8d, $42, $8d, $3c, $8d
	.byte $4c, $8b, $42, $8b, $3c, $8d, $00, $91
	.byte $ff, $0d
	.word @song1ref5
	.byte $8d, $00, $91, $38, $87, $3a, $87, $3c, $91, $3e, $87, $40, $91, $42, $87, $44, $87, $4a, $8f, $00, $f9, $97
@song1ref62:
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb
	.byte $ff, $0c
	.word @song1ref62
	.byte $ff, $0c
	.word @song1ref62
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $fd
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $84
@song1ref91:
	.byte $1a, $97, $00, $93, $28, $8d, $1a, $97, $00, $28, $97, $00, $87, $1c, $97, $00, $93, $2a, $8d, $1c, $97, $00, $2a, $97
	.byte $00, $87
	.byte $ff, $0d
	.word @song1ref91
	.byte $28, $97, $01, $2c, $97, $01, $30, $97, $01, $32, $97, $00, $f9, $8f
	.byte $ff, $0c
	.word @song1ref62
	.byte $ff, $0c
	.word @song1ref62
	.byte $ff, $0c
	.word @song1ref62
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $fd
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $ff, $0c
	.word @song1ref62
	.byte $ff, $0c
	.word @song1ref62
	.byte $ff, $0c
	.word @song1ref62
	.byte $ff, $0c
	.word @song1ref62
	.byte $fd
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
	.byte $ff, $0c
	.word @song1ref62
	.byte $ff, $0c
	.word @song1ref62
	.byte $ff, $0c
	.word @song1ref62
	.byte $ff, $0c
	.word @song1ref62
	.byte $fd
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
	.byte $ff, $0c
	.word @song1ref62
	.byte $ff, $0c
	.word @song1ref62
	.byte $ff, $0c
	.word @song1ref62
	.byte $ff, $0c
	.word @song1ref62
	.byte $fd
	.word @song1ch4loop
@song2ch0:
	.byte $fb, $01
@song2ch0loop:
	.byte $82, $4a, $89, $46, $89, $4a, $97, $00, $93, $40, $8d, $3c, $8d, $38
@song2ref18:
	.byte $8d, $32, $c9, $00, $f9
@song2ref23:
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $fd
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $84, $40, $af, $00, $93, $38, $8d, $36, $8d, $30
	.byte $ff, $32
	.word @song2ref18
	.byte $fd
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
	.byte $80, $52, $87, $00, $50, $87, $00, $52, $87, $00, $a3, $4a, $87, $00, $83, $46, $87, $00, $83, $40, $87, $00, $83, $40
	.byte $87, $00, $83, $40, $87, $00, $83, $40, $87, $00, $83, $40, $87, $00, $f9, $91
	.byte $ff, $2d
	.word @song2ref23
	.byte $fd
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
	.byte $ff, $2d
	.word @song2ref23
	.byte $f9, $f9, $cb, $fd
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
	.byte $ff, $2d
	.word @song2ref23
	.byte $f9, $f9, $cb, $fd
	.word @song2ch4loop
@song3ch0:
	.byte $fb, $01
@song3ch0loop:
	.byte $86
@song3ref5:
	.byte $3c, $89, $00, $83, $3c, $8f, $00, $83, $3c, $83, $42, $95
@song3ref17:
	.byte $3c, $95, $4a, $a1, $46, $a1, $42, $95, $3c, $89, $00, $83, $3c, $8f, $00, $83, $3c, $83, $42, $95, $3c, $95, $4a, $a1
	.byte $46, $a1, $42, $95, $3c, $89, $00, $83, $3c, $8f, $00, $83, $3c, $83, $42, $95, $3c, $95, $4a, $9d, $83, $46, $a1, $42
	.byte $95, $3c, $89, $00, $83, $3c, $8f, $00, $83, $3c, $83, $42, $95, $3c, $95, $46, $a1, $4a, $a1, $4c
@song3ref85:
	.byte $95, $3e, $89, $00, $83, $3e, $8f, $00, $83, $3e, $83, $46, $95, $3e, $95, $4c, $a1, $4a, $a1, $46, $95, $3e, $89, $00
	.byte $83, $3e, $8f, $00, $83, $3e, $83, $46, $8d, $87, $3e, $95, $4c, $a1, $4a, $a1, $46
	.byte $ff, $20
	.word @song3ref85
	.byte $95, $3e, $95, $4a, $a1, $4c, $a1, $4e, $95, $80
@song3ref139:
	.byte $34, $95, $00, $85, $35, $32, $89, $00, $85, $32, $a5, $86, $46, $87, $00, $87, $46, $8b, $00, $87, $47, $4a, $87, $00
	.byte $87, $4a, $99, $80, $2e, $95, $00, $85, $2f, $32, $89, $00, $85, $32, $a5
@song3ref178:
	.byte $86, $4c, $87, $00, $87, $4c, $8b, $00, $87, $4d, $50, $87, $00, $87, $50, $99, $80, $34, $95, $00, $85, $35, $32, $89
	.byte $00, $85, $32, $a5, $86, $54, $87, $00, $87, $54, $89, $81
@song3ref214:
	.byte $00, $87, $55, $56, $87, $00, $87, $56, $99, $80, $2e, $95, $00, $85, $2f, $32, $89, $00, $85, $32, $a5, $86, $5e, $87
	.byte $00, $5e, $87, $00, $87, $5e, $97, $00, $5e, $87, $00, $87, $5e, $8d, $80
	.byte $ff, $1f
	.word @song3ref5
	.byte $8d, $87
	.byte $ff, $2a
	.word @song3ref17
@song3ref261:
	.byte $46, $a1, $4a, $a1, $4c, $95
@song3ref267:
	.byte $86, $3e, $89, $00, $83, $3e, $8f, $00, $83, $3e, $83, $80, $46, $95
@song3ref281:
	.byte $3e, $95, $4c, $a1, $4a, $a1, $46, $95, $86, $3e, $89, $00, $83, $3e, $8f, $00, $83, $3e, $83, $80, $46, $95, $3e, $95
	.byte $4c, $a1, $4a, $a1, $46, $95, $86, $3e, $89, $00, $83, $3e, $8f, $00, $83, $3e, $83, $80, $46, $95, $3e, $95, $4c, $9d
	.byte $83, $4a, $a1, $46, $95, $86, $3e, $89, $00, $83, $3e, $8f, $00, $83, $3e, $83, $80, $46, $95, $3e, $95, $4a, $a1, $4c
	.byte $a1, $4e, $95
@song3ref356:
	.byte $2a, $ad, $24, $ad, $2c, $ad, $24, $ad, $2a, $ad, $24, $8d, $9f, $2c, $ad, $24, $ad, $2a, $ad, $24, $ad, $2c, $ad, $24
	.byte $ad, $2a, $ad, $24, $ad, $2c, $ad, $24, $ad
@song3ref389:
	.byte $2a, $ad, $24, $ad, $2c, $ad, $24, $ad, $2a, $ad, $24, $ad, $2c, $ad, $24, $ad, $2a, $ad, $24, $ad, $2c, $9d, $8f, $24
	.byte $ad, $2a, $ad, $24, $ad, $2c, $ad, $24, $ad
	.byte $ff, $1f
	.word @song3ref5
	.byte $8d, $87
	.byte $ff, $2a
	.word @song3ref17
	.byte $ff, $57
	.word @song3ref261
	.byte $ff, $24
	.word @song3ref139
	.byte $85, $9f
	.byte $ff, $1f
	.word @song3ref178
	.byte $8b
	.byte $ff, $24
	.word @song3ref214
	.byte $80
	.byte $ff, $51
	.word @song3ref5
	.byte $ff, $1f
	.word @song3ref267
	.byte $8d, $87
	.byte $ff, $2a
	.word @song3ref281
	.byte $4a, $a1, $4c, $a1, $4e, $95
	.byte $ff, $21
	.word @song3ref389
	.byte $ff, $21
	.word @song3ref356
	.byte $ff, $51
	.word @song3ref5
	.byte $ff, $1f
	.word @song3ref267
	.byte $8d, $87
	.byte $ff, $2a
	.word @song3ref281
	.byte $4a, $a1, $4c, $a1, $4e, $95
	.byte $ff, $6a
	.word @song3ref139
	.byte $80
	.byte $ff, $1f
	.word @song3ref5
	.byte $8d, $87
	.byte $ff, $2a
	.word @song3ref17
	.byte $ff, $63
	.word @song3ref261
	.byte $fd
	.word @song3ch0loop
@song3ch1:
@song3ch1loop:
@song3ref505:
	.byte $86, $46, $89, $00, $83, $46, $8f, $00, $83, $46, $83, $4c, $95
@song3ref518:
	.byte $46, $95, $52, $a1, $50, $a1, $4c, $95, $46, $89, $00, $83, $46, $8f, $00, $83, $46, $83, $4c, $95, $46, $95, $52, $a1
	.byte $50, $a1, $4c, $95, $46, $89, $00, $83, $46, $8f, $00, $83, $46, $83, $4c, $95, $46, $95, $52, $9d, $83, $50, $a1, $4c
	.byte $95, $46, $89, $00, $83, $46, $8f, $00, $83, $46, $83, $4c, $95, $46, $95
@song3ref581:
	.byte $50, $a1, $52, $a1, $54
@song3ref586:
	.byte $95, $4a, $89, $00, $83, $4a, $8f, $00, $83, $4a, $83, $50, $95, $4a, $95, $56, $a1, $54, $a1, $50, $95, $4a, $89, $00
	.byte $83, $4a, $8f, $00, $83, $4a, $83, $50, $8d, $87, $4a, $95, $56, $a1, $54, $a1, $50
	.byte $ff, $20
	.word @song3ref586
@song3ref630:
	.byte $95, $4a, $95, $54, $a1, $56, $a1, $58, $95
@song3ref639:
	.byte $3e, $95, $00, $85, $3f, $3c, $89, $00, $85, $3c, $a5, $84, $50, $87, $00, $87, $50, $8b, $00, $87, $51, $54, $87, $00
	.byte $87, $54, $99, $86, $38, $95, $00, $85, $39, $3c, $89, $00, $85, $3c, $a5
@song3ref678:
	.byte $84, $56, $87, $00, $87, $56, $8b, $00, $87, $57, $5a, $87, $00, $87, $5a, $99, $86, $3e, $95, $00, $85, $3f, $3c, $89
	.byte $00, $85, $3c, $a5, $84, $5e, $87, $00, $87, $5e, $89, $81
@song3ref714:
	.byte $00, $87, $5f, $62, $87, $00, $87, $62, $99, $86, $38, $95, $00, $85, $39, $3c, $89, $00, $85, $3c, $a5, $84, $68, $87
	.byte $00, $68, $87, $00, $87, $68, $8d, $6c, $87, $00, $6c, $87, $00, $87, $6c, $8d
	.byte $ff, $1f
	.word @song3ref505
	.byte $8d, $87
	.byte $ff, $2a
	.word @song3ref518
	.byte $ff, $25
	.word @song3ref581
@song3ref765:
	.byte $95, $4a, $95, $56, $a1, $54, $a1, $50, $95, $4a, $89, $00, $83, $4a, $8f, $00, $83, $4a, $83, $50, $95, $4a, $95, $56
	.byte $9d, $83, $54, $a1, $50, $95, $4a, $89, $00, $83, $4a, $8f, $00, $83, $4a, $83, $50, $95, $4a, $95, $54, $a1, $56, $a1
	.byte $58, $95, $80
@song3ref816:
	.byte $34, $ad, $2e, $ad, $36, $ad, $2e, $ad, $34, $ad, $2e, $8d, $9f, $36, $ad, $2e, $ad, $34, $ad, $2e, $ad, $36, $ad, $2e
	.byte $ad, $34, $ad, $2e, $ad, $36, $ad, $2e, $ad
@song3ref849:
	.byte $34, $ad, $2e, $ad, $36, $ad, $2e, $ad, $34, $ad, $2e, $ad, $36, $ad, $2e, $ad, $34, $ad, $2e, $ad, $36, $9d, $8f, $2e
	.byte $ad, $34, $ad, $2e, $ad, $36, $ad, $2e, $ad
	.byte $ff, $1f
	.word @song3ref505
	.byte $8d, $87
	.byte $ff, $2a
	.word @song3ref518
	.byte $ff, $25
	.word @song3ref581
	.byte $ff, $32
	.word @song3ref765
	.byte $ff, $24
	.word @song3ref639
	.byte $85, $9f
	.byte $ff, $1f
	.word @song3ref678
	.byte $8b
	.byte $ff, $26
	.word @song3ref714
	.byte $ff, $79
	.word @song3ref505
	.byte $ff, $20
	.word @song3ref586
	.byte $95, $4a, $95, $54, $a1, $56, $a1, $58, $95, $80
	.byte $ff, $21
	.word @song3ref849
	.byte $ff, $21
	.word @song3ref816
	.byte $ff, $79
	.word @song3ref505
	.byte $ff, $20
	.word @song3ref586
	.byte $ff, $75
	.word @song3ref630
	.byte $ff, $1f
	.word @song3ref505
	.byte $8d, $87
	.byte $ff, $2a
	.word @song3ref518
	.byte $ff, $25
	.word @song3ref581
	.byte $ff, $3e
	.word @song3ref765
	.byte $fd
	.word @song3ch1loop
@song3ch2:
@song3ch2loop:
	.byte $80, $46, $85, $00, $8d, $46, $85, $00, $f9, $a3, $46, $85, $00, $8d, $46, $85, $00, $f9, $a3, $46, $85, $00, $8d, $46
	.byte $85, $00, $dd, $bf, $46, $85, $00, $8d, $46, $85, $00, $f9, $a3
@song3ref994:
	.byte $32
@song3ref995:
	.byte $85, $00
@song3ref997:
	.byte $8d, $32, $85, $00, $8d, $32, $85, $00, $8d, $32, $85, $00, $8d, $32, $85, $00, $8d, $32, $85, $00, $8d, $32, $85, $00
	.byte $8d, $32, $85, $00, $8d, $32, $85, $00, $8d, $32, $85, $00, $8d, $32, $85, $00, $85, $87
	.byte $ff, $2b
	.word @song3ref994
	.byte $ff, $28
	.word @song3ref997
@song3ref1045:
	.byte $8d, $3e, $85, $01, $3e, $85, $00, $8d, $3c, $b9, $38, $85, $00, $8d, $38, $85, $00, $8d, $3c, $85, $00, $a5, $38, $85
	.byte $01, $38, $85, $00, $8d, $3c, $b9
@song3ref1076:
	.byte $3e, $85, $00, $8d, $3e, $85, $00, $8d, $42, $85, $00, $a5, $3e, $85, $01, $3e, $85, $00, $8d, $3c, $b9, $46, $85, $00
	.byte $8d, $46, $85, $00, $8d, $4a, $85, $00, $a5, $38, $85, $01, $38, $85, $00, $8d, $3c, $b9, $38, $85, $01, $38, $85, $00
	.byte $99, $3c, $85, $01, $3c, $85, $00, $99
@song3ref1132:
	.byte $2e, $85, $00
@song3ref1135:
	.byte $8d, $2e, $85, $00, $8d, $2e, $85, $00, $8d, $2e, $85, $00, $8d, $2e, $85, $00, $8d, $2e, $85, $00, $8d, $2e, $85, $00
	.byte $8d, $2e, $85, $00, $8d, $2e, $85, $00, $8d, $2e, $85, $00, $8d, $2e, $85, $00, $85, $87
	.byte $ff, $2b
	.word @song3ref1132
	.byte $ff, $28
	.word @song3ref1135
	.byte $ff, $28
	.word @song3ref997
	.byte $ff, $28
	.word @song3ref997
	.byte $ff, $28
	.word @song3ref997
@song3ref1192:
	.byte $8d, $32, $85, $00, $8d, $32, $85, $00, $8d, $34, $87, $00, $a3, $46, $87, $00, $a3, $36, $87, $00, $a3, $46, $87, $00
	.byte $a3, $34, $87, $00, $a3, $46, $87, $00, $83, $9f, $36, $87, $00, $a3, $46, $87, $00, $a3
@song3ref1234:
	.byte $34, $87, $00, $a3, $46, $87, $00, $a3, $36, $87, $00, $a3
@song3ref1246:
	.byte $46, $87, $00, $a3, $34, $87, $00, $a3, $46, $87, $00, $a3, $36, $87, $00, $a3, $46, $87, $00, $a3
@song3ref1266:
	.byte $34, $87, $00, $8b, $34, $87, $00, $8b, $46, $87, $00, $8b, $46, $87, $00, $8b, $36, $87, $00, $8b, $36, $87, $00, $8b
	.byte $46, $87, $00, $8b, $46, $87, $00, $8b
	.byte $ff, $20
	.word @song3ref1266
	.byte $34, $87, $00, $8b, $34, $87, $00, $8b, $46, $87, $00, $8b, $46, $87, $00, $8b, $36, $87, $00, $8b, $36, $85, $81, $00
	.byte $8b, $46, $87, $00, $8b, $46, $87, $00, $8b
	.byte $ff, $20
	.word @song3ref1266
	.byte $ff, $2d
	.word @song3ref1132
	.byte $ff, $2b
	.word @song3ref1132
	.byte $ff, $28
	.word @song3ref1135
	.byte $ff, $28
	.word @song3ref997
	.byte $ff, $28
	.word @song3ref997
	.byte $ff, $28
	.word @song3ref997
	.byte $8d, $32, $85, $00, $8d, $32, $85, $00
	.byte $ff, $1e
	.word @song3ref1045
	.byte $99, $9f
	.byte $ff, $63
	.word @song3ref1076
	.byte $ff, $28
	.word @song3ref1135
	.byte $ff, $28
	.word @song3ref1135
	.byte $8d, $2e
	.byte $ff, $2a
	.word @song3ref995
	.byte $8d, $32, $85, $00, $85, $87
	.byte $ff, $2b
	.word @song3ref994
	.byte $ff, $28
	.word @song3ref997
	.byte $8d
	.byte $ff, $23
	.word @song3ref1234
	.byte $a3, $46, $87, $00, $a3, $36, $87, $00, $93, $8f
	.byte $ff, $34
	.word @song3ref1246
	.byte $34, $87, $00, $8b, $34, $87, $00, $8b, $46, $87, $00, $83, $87, $46, $87, $00, $8b, $36, $87, $00, $8b, $36, $87, $00
	.byte $8b, $46, $87, $00, $8b, $46, $87, $00, $8b
	.byte $ff, $20
	.word @song3ref1266
	.byte $ff, $20
	.word @song3ref1266
	.byte $ff, $2b
	.word @song3ref1132
	.byte $ff, $28
	.word @song3ref1135
	.byte $ff, $28
	.word @song3ref1135
	.byte $8d, $2e
	.byte $ff, $2a
	.word @song3ref995
	.byte $8d, $32, $85, $00, $85, $87
	.byte $ff, $2b
	.word @song3ref994
	.byte $ff, $28
	.word @song3ref997
	.byte $ff, $84
	.word @song3ref1045
	.byte $ff, $2b
	.word @song3ref1132
	.byte $ff, $28
	.word @song3ref1135
	.byte $ff, $28
	.word @song3ref997
	.byte $ff, $28
	.word @song3ref997
	.byte $ff, $28
	.word @song3ref997
	.byte $ff, $21
	.word @song3ref1192
	.byte $fd
	.word @song3ch2loop
@song3ch3:
@song3ch3loop:
	.byte $80, $58, $5c, $00, $91, $58, $5c, $00, $91, $58, $5c, $00, $a9, $58, $5c, $00, $a9, $58, $5c, $00, $a9, $58, $5c, $00
	.byte $91, $58, $5c, $00, $91, $58, $5c, $00, $a9, $58, $5c, $00, $a9, $58, $5c, $00, $a9, $58, $5c, $00, $91, $58, $5c, $00
	.byte $91, $58, $5c, $00, $a9, $58, $5c, $00, $99, $8f, $58, $5c, $00, $a9, $58, $5c, $00, $91, $58, $5c, $00, $91, $58, $5c
	.byte $00, $a9, $58, $5c, $00, $a9
@song3ref1579:
	.byte $58, $5c, $00
@song3ref1582:
	.byte $85, $58, $5c, $00
@song3ref1586:
	.byte $85
@song3ref1587:
	.byte $58, $5c, $00
@song3ref1590:
	.byte $91, $58, $5c, $00, $91, $58, $5c, $00, $91, $58, $5c, $00
@song3ref1602:
	.byte $91, $58, $5c, $00, $91, $58, $5c, $00, $91, $58, $5c, $00, $91, $58, $5c, $00, $91, $58, $5c, $00, $91, $58, $5c, $00
	.byte $91, $58, $5c, $00, $91, $58, $5c, $00, $89, $87
	.byte $ff, $2f
	.word @song3ref1587
	.byte $ff, $24
	.word @song3ref1590
	.byte $85, $58, $5c, $00, $85, $58, $5c, $00, $85, $58, $5c, $00, $85, $58, $5c, $00, $85, $58, $5c, $00, $85
	.byte $ff, $1b
	.word @song3ref1579
	.byte $85, $58, $5c, $00, $85, $58, $5c, $00, $85, $58, $5c, $00, $85, $58, $5c, $00, $85, $58, $5c, $00, $85
	.byte $ff, $1b
	.word @song3ref1579
	.byte $85
@song3ref1691:
	.byte $58, $5c, $00, $85, $58, $5c, $00
@song3ref1698:
	.byte $85, $58, $5c, $00, $85
@song3ref1703:
	.byte $58, $5c, $00, $85, $58, $5c, $00, $85, $58, $5c, $00, $85, $58, $5c, $00, $85, $58, $5c, $00, $91, $58, $5c, $00, $91
	.byte $58, $5c, $00, $81, $8f, $58, $5c, $00, $91
	.byte $ff, $1f
	.word @song3ref1691
	.byte $85, $58, $5c, $00, $91
	.byte $ff, $1f
	.word @song3ref1691
	.byte $ff, $2c
	.word @song3ref1586
	.byte $89, $87
	.byte $ff, $2f
	.word @song3ref1587
	.byte $ff, $24
	.word @song3ref1590
	.byte $ff, $34
	.word @song3ref1582
	.byte $ff, $28
	.word @song3ref1590
	.byte $81, $8f
	.byte $ff, $1b
	.word @song3ref1587
	.byte $85, $58, $5c, $00, $85, $58, $5c, $00, $91, $58, $5c, $00, $91
	.byte $ff, $33
	.word @song3ref1579
	.byte $89, $87
	.byte $ff, $2f
	.word @song3ref1587
	.byte $ff, $20
	.word @song3ref1590
	.byte $85, $58, $5c, $00, $85
	.byte $ff, $37
	.word @song3ref1579
	.byte $ff, $28
	.word @song3ref1590
	.byte $81, $8f
	.byte $ff, $1b
	.word @song3ref1587
	.byte $85, $58, $5c, $00, $85, $58, $5c, $00, $91
	.byte $ff, $1b
	.word @song3ref1703
	.byte $ff, $22
	.word @song3ref1602
	.byte $ff, $2f
	.word @song3ref1587
	.byte $ff, $24
	.word @song3ref1590
	.byte $ff, $34
	.word @song3ref1582
	.byte $ff, $28
	.word @song3ref1590
	.byte $81, $8f
	.byte $ff, $1b
	.word @song3ref1587
	.byte $85, $58, $5c, $00, $85, $58, $5c, $00, $91, $58, $5c, $00, $91
	.byte $ff, $1f
	.word @song3ref1691
	.byte $85, $58, $5c, $00, $91, $58, $5c, $00, $91, $58, $5c, $00, $91, $58, $5c, $00, $91
	.byte $ff, $1f
	.word @song3ref1691
	.byte $85, $58, $5c, $00, $91, $58, $5c, $00, $91, $58, $5c, $00, $91, $58, $5c, $00, $91
	.byte $ff, $1f
	.word @song3ref1691
	.byte $85, $58, $5c, $00, $91, $58, $5c, $00, $91, $58, $5c, $00, $91, $58, $5c, $00, $91
	.byte $ff, $1f
	.word @song3ref1691
	.byte $85, $58, $5c, $00, $91
	.byte $ff, $1f
	.word @song3ref1691
	.byte $ff, $30
	.word @song3ref1586
	.byte $ff, $28
	.word @song3ref1590
	.byte $81, $8f
	.byte $ff, $27
	.word @song3ref1587
	.byte $ff, $30
	.word @song3ref1582
	.byte $89, $87
	.byte $ff, $2f
	.word @song3ref1587
@song3ref1944:
	.byte $91, $58, $5c, $00, $91
@song3ref1949:
	.byte $58, $5c, $00, $91, $58, $5c, $00, $91, $58, $5c, $00, $91, $58, $5c, $00, $91, $58, $5c, $00, $85, $58, $5c, $00, $85
	.byte $58, $5c, $00, $91, $58, $5c, $00, $91
	.byte $ff, $37
	.word @song3ref1579
	.byte $ff, $28
	.word @song3ref1590
	.byte $81, $8f
	.byte $ff, $23
	.word @song3ref1587
	.byte $85, $58, $5c, $00, $85
	.byte $ff, $33
	.word @song3ref1579
	.byte $89, $87
	.byte $ff, $2f
	.word @song3ref1587
	.byte $ff, $24
	.word @song3ref1944
	.byte $85, $58, $5c, $00, $85
	.byte $ff, $37
	.word @song3ref1579
	.byte $ff, $28
	.word @song3ref1590
	.byte $81, $8f
	.byte $ff, $27
	.word @song3ref1587
	.byte $ff, $30
	.word @song3ref1582
	.byte $89, $87
	.byte $ff, $2f
	.word @song3ref1587
	.byte $ff, $25
	.word @song3ref1944
	.byte $ff, $1f
	.word @song3ref1691
	.byte $85
	.byte $ff, $1b
	.word @song3ref1949
	.byte $ff, $20
	.word @song3ref1698
	.byte $91, $58, $5c, $00, $91
	.byte $ff, $1f
	.word @song3ref1691
	.byte $85, $58, $5c, $00, $91, $58, $5c, $00, $91, $58, $5c, $00, $81, $8f, $58, $5c, $00, $91
	.byte $ff, $1f
	.word @song3ref1691
	.byte $85, $58, $5c, $00, $91
	.byte $ff, $1f
	.word @song3ref1691
	.byte $ff, $2c
	.word @song3ref1586
	.byte $89, $87
	.byte $ff, $2f
	.word @song3ref1587
	.byte $ff, $24
	.word @song3ref1590
	.byte $ff, $34
	.word @song3ref1582
	.byte $ff, $28
	.word @song3ref1590
	.byte $81, $8f
	.byte $ff, $1b
	.word @song3ref1587
	.byte $85, $58, $5c, $00, $85, $58, $5c, $00, $91, $58, $5c, $00, $91
	.byte $ff, $33
	.word @song3ref1579
	.byte $89, $fd
	.word @song3ch3loop
@song3ch4:
@song3ch4loop:
	.byte $02, $00, $93, $02, $00, $f9, $a9, $02, $00, $93, $02, $00, $f9, $a9, $02, $00, $93, $02, $00, $e3, $bf, $02, $00, $93
	.byte $02, $00, $93, $02, $00, $ab, $02, $00, $ab, $04, $89, $04, $89, $04, $8d, $00, $85
@song3ref2166:
	.byte $02, $00, $ab
@song3ref2169:
	.byte $04, $8d, $00, $9d, $02, $00, $93, $02, $00, $93, $04, $8d, $00, $9d, $02, $00, $ab, $04, $8d, $00, $9d, $02, $00, $93
	.byte $02, $00, $93, $04, $8d, $00, $9d
	.byte $ff, $21
	.word @song3ref2166
	.byte $85, $04, $89, $04, $89
@song3ref2208:
	.byte $04, $89, $04, $89, $02, $00, $87, $04, $8d, $00, $91
@song3ref2219:
	.byte $02, $00, $93, $02, $00, $93, $02, $00, $93, $04, $8d, $00, $9d, $04, $89, $04, $89, $02, $00, $87, $04, $8d, $00, $91
	.byte $02, $00, $93, $02, $00, $93, $02, $00, $93, $04, $8d, $00, $9d, $04, $89, $04, $89, $02, $00, $87, $04, $8d, $00, $91
	.byte $02, $00, $93, $02, $00, $93, $02, $00, $83, $8f, $04, $8d, $00, $9d, $04, $89, $04, $89, $02, $00, $87, $04, $8d, $00
	.byte $91, $02, $00, $93, $04, $89, $04, $8d, $00, $91, $04, $89, $04, $8d, $00, $91
	.byte $ff, $22
	.word @song3ref2166
	.byte $ff, $21
	.word @song3ref2166
	.byte $85, $04, $89, $04, $89
	.byte $ff, $22
	.word @song3ref2166
@song3ref2321:
	.byte $02, $00, $ab, $04, $8d, $00, $9d, $02, $00, $93, $02, $00, $83, $8f
@song3ref2335:
	.byte $04, $8d, $00, $9d, $02, $00, $ab, $04, $8d, $00, $9d, $04, $89, $04, $89, $04, $8d, $00, $85, $04, $8d, $00, $85, $04
	.byte $89, $04, $89, $02, $00, $93, $02, $00, $93
	.byte $ff, $1f
	.word @song3ref2169
	.byte $02, $00, $93, $02, $00, $93
	.byte $ff, $1c
	.word @song3ref2169
@song3ref2380:
	.byte $89, $04, $89, $04, $89, $04, $89, $02, $00, $93, $02, $00, $93, $04, $8d, $00, $85, $02, $00, $93, $02, $00, $93, $02
	.byte $00, $93, $04, $8d, $00, $85, $02, $00, $93, $02, $00, $93, $02, $00, $93, $04, $8d, $00, $85, $02, $00, $93, $02, $00
	.byte $93, $02, $00, $93, $04, $8d, $00, $85, $04, $8d, $00, $85, $02, $00, $93, $02, $00, $93, $04, $8d, $00, $85, $02, $00
	.byte $93, $02, $00, $93, $02, $00, $83, $8f
@song3ref2460:
	.byte $04, $8d, $00, $85, $02, $00, $93, $02, $00, $93, $02, $00, $93, $04, $8d, $00, $85, $02, $00, $93, $04, $89, $04, $89
	.byte $04, $8d, $00, $85, $04, $89, $04, $89, $04, $89, $04, $89
	.byte $ff, $22
	.word @song3ref2166
	.byte $ff, $21
	.word @song3ref2166
	.byte $85, $04, $89, $04, $89
	.byte $ff, $22
	.word @song3ref2166
	.byte $ff, $29
	.word @song3ref2321
	.byte $ff, $22
	.word @song3ref2208
	.byte $89, $87
	.byte $ff, $33
	.word @song3ref2219
	.byte $04, $89, $04, $8d, $00, $91, $04, $89, $04, $8d, $00, $91
	.byte $ff, $22
	.word @song3ref2166
@song3ref2536:
	.byte $02, $00, $ab
@song3ref2539:
	.byte $04, $8d, $00, $9d, $02, $00, $93, $02, $00, $83, $8f, $04, $8d, $00, $9d, $02, $00, $ab, $04, $8d, $00, $9d, $02, $00
	.byte $93, $02, $00, $93, $04, $8d, $00, $85, $04, $89, $04, $89
	.byte $ff, $22
	.word @song3ref2166
	.byte $02, $00, $ab, $04, $8d, $00, $9d, $02, $00, $93, $02, $00, $93
	.byte $ff, $21
	.word @song3ref2335
	.byte $ff, $1f
	.word @song3ref2169
	.byte $02, $00, $93, $02, $00, $93
	.byte $ff, $1d
	.word @song3ref2539
	.byte $ff, $4e
	.word @song3ref2380
	.byte $93
	.byte $ff, $24
	.word @song3ref2460
	.byte $ff, $22
	.word @song3ref2166
	.byte $ff, $27
	.word @song3ref2536
	.byte $ff, $22
	.word @song3ref2166
	.byte $02, $00, $ab, $04, $8d, $00, $9d, $02, $00, $93, $02, $00, $93
	.byte $ff, $1b
	.word @song3ref2335
	.byte $ff, $63
	.word @song3ref2208
	.byte $ff, $22
	.word @song3ref2166
	.byte $ff, $21
	.word @song3ref2166
	.byte $85, $04, $89, $04, $89
	.byte $ff, $22
	.word @song3ref2166
	.byte $ff, $2f
	.word @song3ref2321
	.byte $04, $8d, $00, $9d, $02, $00, $93, $02, $00, $93, $04, $8d, $00, $9d, $02, $00, $ab, $04, $8d, $fd
	.word @song3ch4loop
