; This file is for the FamiTone2 library and was generated by FamiStudio

sounds:
	.word @ntsc
	.word @pal
@ntsc:
	.word @sfx_ntsc_0

@pal:
	.word @sfx_pal_0

@sfx_ntsc_0:
	.byte $82,$01,$81,$fc,$80,$bf,$89,$f0,$01,$81,$93,$01,$81,$53,$01,$81
	.byte $1d,$01,$82,$00,$81,$fe,$02,$00
@sfx_pal_0:
	.byte $82,$01,$81,$d8,$80,$bf,$89,$f0,$01,$81,$76,$01,$81,$3b,$01,$81
	.byte $09,$82,$00,$81,$ec,$02,$00
